# Generated by Django 5.0 on 2024-06-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='img',
            field=models.ImageField(default='\\meida\\default.jpg', upload_to='meida/profile'),
        ),
    ]
