# Generated by Django 5.0 on 2024-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_profiles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='img',
            field=models.ImageField(default='/meida/default.jpg', upload_to='meida/profile/'),
        ),
    ]
