# Generated by Django 5.2.7 on 2025-10-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_profiles_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='img',
        ),
    ]
