# Generated by Django 5.2.7 on 2025-12-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcateringweb', '0002_service_remove_menuselection_option_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='service',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='service_type',
            field=models.CharField(choices=[('party_pack', 'Party Pack'), ('lunchbox', 'Lunchbox'), ('catering', 'Catering')], default='party_pack', max_length=20),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
