# Generated by Django 5.2.7 on 2026-01-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcateringweb', '0004_order_delivery_address_order_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'In Process'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
    ]
